spring:
  profiles:
    active: mysqlDB  #切换指定的数据源.
  #jpa 配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  #如果表不存在，则自动新建，如果表结构发生变化，则自动更新

  # quartz 调度器配置
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 15 # 开启15个线程
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc


---
spring:
  profiles: h2DB
  #h2 数据源配置
  datasource:
    username: sa
    password: 123456
    #持久化到本地磁盘，使用混合模式，默认情况下，H2 只运行一个进程访问，true 表示可以多个进程可以访问同一个数据库
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver

  #H2 Web 控制台配置，启用 h2 Console 控制台，并设置访问路径
  h2:
    console:
      enabled: true
      path: /h2_console

---
spring:
  profiles: mysqlDB
  datasource:
    username: root
    password: root
    # spring boot 2.1.5 搭配 mysql 驱动 8.0.16，高版本 mysql 驱动的 driver-class-name 值要带 cj;url 值要带时区 serverTimezone
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver